# Generated by Django 5.1.1 on 2024-10-29 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturalworld_d', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default='Descripcion no disponible'),
            preserve_default=False,
        ),
    ]
