# Generated by Django 5.1.2 on 2024-12-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturalworld_d', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportorder',
            name='additional_product_description',
        ),
        migrations.RemoveField(
            model_name='transportorder',
            name='address',
        ),
        migrations.RemoveField(
            model_name='transportorder',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='transportorder',
            name='classification_data',
        ),
        migrations.RemoveField(
            model_name='transportorder',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='transportorder',
            name='count_of_generated_orders',
        ),
        migrations.RemoveField(
            model_name='transportorder',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='transportorder',
            name='delivery_type_code',
        ),
        migrations.RemoveField(
            model_name='transportorder',
            name='delivery_zone_id',
        ),
        migrations.RemoveField(
            model_name='transportorder',
            name='destination_coverage_area_name',
        ),
        migrations.RemoveField(
            model_name='transportorder',
            name='distribution_description',
        ),
        migrations.RemoveField(
            model_name='transportorder',
            name='generic_string1',
        ),
        migrations.RemoveField(
            model_name='transportorder',
            name='generic_string2',
        ),
        migrations.RemoveField(
            model_name='transportorder',
            name='group_reference',
        ),
        migrations.RemoveField(
            model_name='transportorder',
            name='label_data',
        ),
        migrations.RemoveField(
            model_name='transportorder',
            name='label_version',
        ),
        migrations.RemoveField(
            model_name='transportorder',
            name='printed_date',
        ),
        migrations.RemoveField(
            model_name='transportorder',
            name='product_description',
        ),
        migrations.RemoveField(
            model_name='transportorder',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='transportorder',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='transportorder',
            name='service_description',
        ),
        migrations.RemoveField(
            model_name='transportorder',
            name='service_description_full',
        ),
        migrations.AlterField(
            model_name='transportorder',
            name='certificate_number',
            field=models.BigIntegerField(blank=True, help_text='Número del certificado asociado a la orden de transporte', null=True),
        ),
        migrations.AlterField(
            model_name='transportorder',
            name='fecha_generacion',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha en que se generó la orden'),
        ),
    ]
