# Generated by Django 5.1.1 on 2024-10-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturalworld_d', '0002_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='altura',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='ancho',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='largo',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
