# Generated by Django 5.1.1 on 2024-10-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturalworld_d', '0003_producto_altura_producto_ancho_producto_largo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='altura',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ancho',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='largo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
