# Generated by Django 5.1.1 on 2024-11-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturalworld_d', '0004_transportorder_label_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionRemitente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Remitente Fijo', max_length=100)),
                ('telefono', models.CharField(default='123456789', max_length=15)),
                ('email', models.EmailField(default='remitente@correo.com', max_length=254)),
            ],
        ),
    ]
