# Generated by Django 5.1.1 on 2024-10-31 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturalworld_d', '0004_alter_producto_altura_alter_producto_ancho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(default='default_value', max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='valor_declarado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='altura',
            field=models.IntegerField(help_text='Altura en cm'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ancho',
            field=models.IntegerField(help_text='Ancho en cm'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='largo',
            field=models.IntegerField(help_text='Largo en cm'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='peso',
            field=models.DecimalField(decimal_places=2, help_text='Peso en kg', max_digits=5),
        ),
    ]
