# Generated by Django 5.1.1 on 2024-11-24 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturalworld_d', '0005_configuracionremitente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='direccion',
            field=models.ForeignKey(blank=True, help_text='Dirección asociada al pedido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='naturalworld_d.direccion'),
        ),
    ]
