# Generated by Django 5.1.1 on 2024-11-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturalworld_d', '0006_pedido_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionremitente',
            name='comuna',
            field=models.CharField(default='Comuna Remitente', max_length=100),
        ),
        migrations.AddField(
            model_name='configuracionremitente',
            name='delivery_on_commercial_office',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuracionremitente',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracionremitente',
            name='street_name',
            field=models.CharField(default='Calle del Remitente', max_length=100),
        ),
        migrations.AddField(
            model_name='configuracionremitente',
            name='street_number',
            field=models.CharField(default='1234', max_length=10),
        ),
    ]
