# Generated by Django 5.1.1 on 2024-11-24 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naturalworld_d', '0007_configuracionremitente_comuna_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfiguracionRemitente',
        ),
    ]
