# Generated by Django 5.1.1 on 2024-11-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturalworld_d', '0008_delete_configuracionremitente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviogenerado',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('generado', 'Generado'), ('en_transito', 'En Tránsito'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
