# Generated by Django 4.0.5 on 2024-12-01 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturalworld_d', '0009_alter_enviogenerado_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default=123, upload_to='productos'),
            preserve_default=False,
        ),
    ]
