# Generated by Django 5.1.2 on 2024-11-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturalworld_d', '0012_cliente_pedido_rut_alter_pedido_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='referencia_externa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
