# Generated by Django 5.1.2 on 2024-11-17 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naturalworld_d', '0013_pago_referencia_externa'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pedidoproducto',
            unique_together={('pedido', 'producto')},
        ),
    ]
