# Generated by Django 5.1.2 on 2024-11-17 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturalworld_d', '0015_alter_pedido_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoproducto',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_productos', to='naturalworld_d.pedido'),
        ),
    ]
