# Generated by Django 5.1.2 on 2024-11-18 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturalworld_d', '0023_alter_cliente_options_remove_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidoproducto',
            old_name='precio',
            new_name='precio_unitario',
        ),
        migrations.AlterUniqueTogether(
            name='pedidoproducto',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='productos',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='rut',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoproducto',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pedidoproducto',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='naturalworld_d.pedido'),
        ),
    ]
