# Generated by Django 4.0.5 on 2024-11-19 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturalworld_d', '0026_alter_producto_imagen_alter_producto_tipo_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado_pedido',
            field=models.CharField(default='En Preparación', max_length=40),
        ),
    ]
